// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           23
// Async Callback (empty):               1
// Total number of exported functions:  25

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    reputation
    (
        createSpace
        createCampaign
        claim
        addKycKey
        checkKycKey
        whitelistParticipants
        delistParticipants
        pauseSpace
        unpauseSpace
        pause
        unpause
        setAdministrator
        getCampaigns
        getCampaignWhiteList
        getState
        getSpaceState
        getAdministrator
        getSpaces
        getSpaceCampaigns
        viewSpace
        viewClaims
        getIndividualCampaign
        getKycNotification
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
